version: '3.8'

services:
  # Base de datos MongoDB
  mongodb:
    image: mongo:6.0
    container_name: lime-pathsys-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: lime_pathsys
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - lime-pathsys-network

  # Backend FastAPI
  backend:
    build: 
      context: ./Back-End
      dockerfile: Dockerfile
    container_name: lime-pathsys-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://admin:password123@mongodb:27017/lime_pathsys?authSource=admin
      DATABASE_NAME: lime_pathsys
      SECRET_KEY: your-super-secret-key-change-in-production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      BACKEND_CORS_ORIGINS: '["http://localhost:3000", "http://localhost:5173", "http://localhost:80"]'
    depends_on:
      - mongodb
    volumes:
      - ./Back-End:/app
    networks:
      - lime-pathsys-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend Vue.js
  frontend:
    build:
      context: ./Front-End
      dockerfile: Dockerfile
    container_name: lime-pathsys-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - lime-pathsys-network

  # Frontend desarrollo (comentado por defecto)
  # frontend-dev:
  #   image: node:18-alpine
  #   container_name: lime-pathsys-frontend-dev
  #   working_dir: /app
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./Front-End:/app
  #   command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
  #   depends_on:
  #     - backend
  #   networks:
  #     - lime-pathsys-network

volumes:
  mongodb_data:
    driver: local

networks:
  lime-pathsys-network:
    driver: bridge
